<?php

namespace Richpolis\UsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HijoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HijoRepository extends EntityRepository
{
    public function queryFindHijos($buscar = "")
    {
        $em = $this->getEntityManager();
        if(strlen($buscar)==0){
            $consulta = $em->createQuery('SELECT a,p '
                . 'FROM UsuariosBundle:Hijo a '
                . 'JOIN a.papa p '    
                . 'ORDER BY a.nombre ASC, p.username ASC');
        }else{
            $consulta = $em->createQuery("SELECT a,p "
                . "FROM UsuariosBundle:Hijo a "
                . "JOIN a.papa p "
                . "WHERE a.nombre LIKE :nombre OR a.apodo LIKE :apodo OR p.username LIKE :username  "
                . "ORDER BY a.nombre ASC, p.username ASC");
            $consulta->setParameters(array(
                'nombre' => "%".$buscar."%",
                'apodo' => "%".$buscar."%",
                'username' => "%".$buscar."%"
            ));
        }
        return $consulta;
    }
    
    public function findHijos($buscar = ""){
        return $this->queryFindHijos($buscar)->getResult();
    }
    
    public function queryHijosForUser(\Symfony\Component\Security\Core\SecurityContext $context)
    {
        $em = $this->getEntityManager();
        $usuario = $context->getToken()->getUser();
        $consulta = $em-createQueryBuilder('h')
                        ->where('h.papa=:papa')
                        ->orderBy('h.sexo', 'ASC')
                        ->addOrderBy('h.nombre','ASC')    
                        ->setParameter('papa',$usuario->getId());
        return $consulta;
    }
}
