frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

historias:
    resource: "@HistoriasBundle/Controller/"
    type:     annotation
    prefix:   /

usuarios:
    resource: "@UsuariosBundle/Controller/"
    type:     annotation
    prefix:   /

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /login
    
facebook_login:
    pattern: /login/check-facebook

twitter_login:
    pattern: /login/check-twitter
 
google_login:
    pattern: /login/check-google

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"