frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

historias:
    resource: "@HistoriasBundle/Controller/"
    type:     annotation
    prefix:   /

usuarios:
    resource: "@UsuariosBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"