backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

historias:
    resource: "@HistoriasBundle/Controller/"
    type:     annotation
    prefix:   /

usuarios:
    resource: "@UsuariosBundle/Controller/"
    type:     annotation
    prefix:   /
