security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Richpolis\UsuariosBundle\Entity\Usuario:
          algorithm: sha512
          encode-as-base64: true
          iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USUARIO
        ROLE_SUPER_ADMIN: [ROLE_USUARIO, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: Richpolis\UsuariosBundle\Entity\Usuario, property: username }

    firewalls:
      dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false
        main:
            pattern: ^/
            form_login:
                provider: user_db
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook:   "/login/check-facebook"
                    twitter:    "/login/check-twitter"
                    google:     "/login/check-google"
                login_path:    /connect
                failure_path:  /connect
                oauth_user_provider:
                    #this is my custom user provider, will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:       true
            anonymous:    true
 
        login:
            pattern:  ^/login$
            security: false
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/h, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: [ROLE_USUARIO] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
