# 
parameters:
    my_user_provider.class: Richpolis\UsuariosBundle\Security\Core\User\UserProvider
    my_user.class: Richpolis\UsuariosBundle\Entity\Usuario
    
services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@doctrine,%my_user.class%,{facebook: facebook_id, twitter: twitter_id, google: google_id }]
        
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    login_listener:
        class: Richpolis\FrontendBundle\Listener\LoginListener
        arguments: [@service_container,@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }

    richpolis_frontend.twig.translate_date_extension:
        class: Richpolis\FrontendBundle\Twig\TranslateDateExtension
        tags:
            - { name: twig.extension }

    richpolis_frontend.twig.string_month_extension:
        class: Richpolis\FrontendBundle\Twig\StringMonthExtension
        tags:
            - { name: twig.extension }
