<?php

namespace Richpolis\HistoriasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponenteRepository extends EntityRepository
{
    public function getMaxPosicion($historia){
        $em=$this->getEntityManager();
       
        $query=$em->createQuery('
            SELECT MAX(c.position) as value 
            FROM HistoriasBundle:Componente c 
            WHERE c.historia =:historia
            ORDER BY c.position ASC
        ')->setParameter('historia', $historia);
        
        $max=$query->getResult();
        return $max[0]['value'];
    }
}
