<?php

namespace Richpolis\HistoriasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriaRepository extends EntityRepository
{
    public function queryFindHistorias($buscar = "")
    {
        $em = $this->getEntityManager();
        if(strlen($buscar)==0){
            $consulta = $em->createQuery('SELECT a '
                . 'FROM HistoriasBundle:Historia a '
                . 'ORDER BY a.fecha ASC');
        }else{
            $consulta = $em->createQuery("SELECT a "
                . "FROM HistoriasBundle:Historia a "
                . "WHERE a.historia LIKE :historia  "
                . "ORDER BY a.historia ASC");
            $consulta->setParameters(array(
                'historia' => "%".$buscar."%",
            ));
        }
        return $consulta;
    }
    
    public function findHistorias($buscar = ""){
        return $this->queryFindHistorias($buscar)->getResult();
    }
}
