<?php

namespace Richpolis\HistoriasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriaRepository extends EntityRepository
{
}
